# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X internal/cmd.Version=bla


# .goreleaser.yml
nfpms:
#  see https://goreleaser.com/customization/nfpm/
  -
    id: default
    homepage: https://github.com/AndresBott/videoconv
    maintainer: AndresBott <contact@andresbott.com>
    description: Batch video conversion based on directory observation.
    license: GNU Lesser General Public License v2.1
    formats:
      - deb
      - rpm
    dependencies:
      - ffmpeg
    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
